version: '3'
services:
  rent_db:
    image: mysql:8
    env_file:
      - mysql.dev.env
    ports:
      - 3306:3306
  rent_server:
    build:
      context: ..
      dockerfile: docker/express/DockerfileDev
    depends_on:
      - rent_db
    env_file:
      - express.dev.env
    entrypoint: yarn start:dev
    ports:
      - 3000:3000
    volumes:
      - ..:/home/node/app
      - /home/node/app/node_modules
